#cloud-config
users:
  - name: voi
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    passwd: ""

# update & install necessary packages
package_update: true
package_upgrade: true
packages:
  - fail2ban
  - openssh-server

write_files:
  # copy the ssh key that was added at creation
  - path: /home/voi/.ssh/authorized_keys
    content: $(cat /root/.ssh/authorized_keys)
    owner: voi:voi
    permissions: '0600'
  - path: /etc/ssh/sshd_config
    content: |
      AllowAgentForwarding no
      AllowTcpForwarding no
      AllowUsers voi
      AuthorizedKeysFile .ssh/authorized_keys
      ClientAliveCountMax 1
      ClientAliveInterval 300
      KbdInteractiveAuthentication no
      MaxAuthTries 2
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      X11Forwarding no
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 10m
      findtime = 10m
      maxretry = 3

      [sshd]
      enabled = true
      port = ssh
      logpath = %(sshd_log)s

runcmd:
  - systemctl restart sshd
#  - systemctl enable fail2ban
#  - systemctl restart fail2ban
#  - fail2ban-client reload

final_message: "SSH security configurations and Fail2Ban are successfully applied."
