#cloud-config
users:
  - name: voi
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: true

# update & install necessary packages
package_update: true
package_upgrade: true
packages:
  - fail2ban
  - openssh-server

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      PermitRootLogin no
      AllowUsers voi
      ClientAliveInterval 300
      ClientAliveCountMax 1
      MaxAuthTries 2
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      PasswordAuthentication no
      PubkeyAuthentication yes
      KbdInteractiveAuthentication no
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 10m
      findtime = 10m
      maxretry = 3

      [sshd]
      enabled = true
      port = 22
      logpath = %(sshd_log)s

runcmd:
  - mkdir -p /home/voi/.ssh
  - cp /root/.ssh/authorized_keys /home/voi/.ssh/authorized_keys # copy the ssh key that was added at creation
  - systemctl restart sshd
  - systemctl enable fail2ban
  - systemctl restart fail2ban
  - fail2ban-client reload

final_message: "SSH security configurations and Fail2Ban are successfully applied."
