#cloud-config
debug: true

users:
  - name: voi
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

# update & install necessary packages
package_update: true
package_upgrade: true
packages:
#  - fail2ban
  - openssh-server

bootcmd:
  # update the ssh config to use password-less login and only allow the voi user
  - |
    cat <<EOF >> /etc/ssh/sshd_config
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitRootLogin no
    PasswordAuthentication no
    PubkeyAuthentication yes
    MaxAuthTries 3
    ClientAliveInterval 300
    ClientAliveCountMax 1
    AuthorizedKeysFile .ssh/authorized_keys
    AllowUsers voi
    EOF

runcmd:
  # setup fail2ban
#  - systemctl enable fail2ban
#  - cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
#  - sed -i 's/^enabled = false/enabled = true/' /etc/fail2ban/jail.local
#  - sed -i 's/^port = ssh/port = 22/' /etc/fail2ban/jail.local
#  - systemctl restart fail2ban

final_message: "SSH security configurations and Fail2Ban are successfully applied."
