name: "Pull Request Checks"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate_pr_title:
    name: "Validate PR Title"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-dependencies
      - name: "📥 Get PR Title"
        id: get_pr_title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return data.title;
      - name: "✅ Validate"
        run: echo "${{ steps.get_pr_title.outputs.result }}" | npx commitlint
